### ISSUE TITLE
Add the ability to save multiple scrrolls

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/scrroll-in#79]
Since we can only save one scrroll for any particular page right now, we received a few requests from the users for having the ability to save multiple scrrolls.
<img width="968" alt="Image 2020-09-30 at 10 49 37 PM" src="https://user-images.githubusercontent.com/21277179/94718336-404d6800-036f-11eb-8743-0c9885896063.png">

A few things that you need to keep in mind while building this are -

- When the user clicks on the save/add more a prompt should ask the name of the scrroll

- You will need to modify the existing saving [data structure](https://github.com/devfolioco/scrroll-in/blob/8dc84ac78863c7d01cdd850a6238b6b8f84baa91/save.js#L13) so that it doesn't break any previously saved scrrolls.

- The user can select the scrroll from the saved scrrolls (the selected scrroll is the blue one) and modify, the "Fetch Scrroll", "Update" and "Delete" would work in respect to that scrroll

- The latest scrroll should be selected by default when the user opens the popup.

You can find the Figma design file [here](https://www.figma.com/file/GGHxsmNS9AhOq4Y1Co9wkT/Scrroll-in?node-id=0%3A1)

**Comment by dewanshrawat15** [comment]
@prateek3255 I'd like to work on this.

**Comment by prateek3255** [comment]
Yeah, sure go ahead

**Comment by mariusjohan** [comment]
I was thinking just to save each "data structure" in a new list which is displayed as show, just with multiple instead of one. So where can I integrate this feature?

**Comment by mariusjohan** [comment]
I just realised, is it multiple

**Comment by prateek3255** [comment]
I would recommend going through the README and testing it out locally to understand how it works

**Comment by mariusjohan** [comment]
I see, so you want save multiple places on a website?

**Comment by prateek3255** [comment]
> I see, so you want save multiple places on a website?

Yes

**Comment by mariusjohan** [comment]
In this case, I would maybe save it as an ID instead, but still print it out as the url (and position percentage). Or what?

**Comment by prateek3255** [comment]
Yeah, you need to add the ID and name you would take from the input prompt while saving.

**Comment by mariusjohan** [comment]
So how I want this to be built is by having the url as an ID. This ID then stores a list of page yoffsets, but whenever you the url has as list with a length over 1, there should be a popup displaying each percentage from the top.

in psuedo code:
1) save url
2) Check of the url already exists
3) if it does append the new data to the list

The problem is just that this codebase is very uncommented, thus I'm having quite a hard time figuring out what the different components do. Maybe you can explain to me what I should change in what file?

**Comment by mariusjohan** [comment]
Like the saving mechanism how does it exactly work and how can I change it into a list instead of a dictionary (or whatever you're using)

**Comment by shikharsaxena98** [comment]
Doesn't look like anyone is working on this. I will take it up.

**Comment by prateek3255** [comment]
> Doesn't look like anyone is working on this. I will take it up.

Sure please go ahead

**Comment by shikharsaxena98** [comment]
This task needs to be broken into sub-tasks. I have done the backend integration (saving the scroll, fetching the scrolls etc.) but still, adding a new button in the widget popup, displaying all available scrolls need to be integrated, I will commit a working version with the new features so that the UI can be designed.
